const articles={
desk:{label:"仕事道具",title:"在宅ワークの机選び。幅・奥行き・高さを先に決める理由",intro:"机は一度置くと簡単には動かせません。デザインを見る前に、使う機器と部屋の寸法を整理しましょう。",sections:[["1. 置く物を一覧にする","ノートPCだけか、外部モニターや書類も広げるかで必要な天板は変わります。道具を実際に並べ、左右に各10cmほどの余白を足すと目安を作れます。"],["2. 奥行きは画面との距離で考える","大型モニターを使うなら、画面との適切な距離を保てる奥行きが必要です。壁やモニターアームの厚みも忘れずに測ります。"],["3. 高さは椅子とセットで確認","肩が上がらず、肘が自然に曲がる位置が基本です。固定高の机では椅子の調整幅、昇降机では最低・最高位置を確認しましょう。"],["購入前チェック","搬入経路、コンセント位置、脚の形、耐荷重、返品条件まで確認すると失敗を減らせます。"]]},
chair:{label:"仕事道具",title:"ワークチェアは「高機能」より身体との相性で選ぶ",intro:"調整機能の多さは魅力ですが、身体に合わなければ活かせません。可能なら実際に座って確かめましょう。",sections:[["試座で見る5項目","足裏が床につくか、座面前端が膝裏を圧迫しないか、背もたれが腰を支えるか、肘が自然に置けるか、操作が無理なくできるかを確認します。"],["長時間座って判断する","最初の数分の柔らかさだけでなく、20分ほど座ったときの姿勢変化や熱のこもり方にも注目します。"],["忘れがちな条件","机の下に肘掛けが収まるか、床材にキャスターが合うか、保証や部品交換の条件も比較しましょう。"]]},
course:{label:"学び",title:"オンライン講座を選ぶ前に決めたい、学習のゴールと期限",intro:"講座選びは、教材の量より「受講後に何ができれば成功か」を決めるところから始まります。",sections:[["ゴールを行動で書く","「詳しくなる」ではなく「3か月後にポートフォリオを1本完成させる」のように、確認できる行動にします。"],["使える時間を計算する","週の学習可能時間に受講期間を掛け、教材量と比べます。予定の7割程度で組むと、忙しい週にも続けやすくなります。"],["サポートを比較する","質問への回答時間、添削の回数、コミュニティの有無、解約・返金条件を公式情報で確認します。無料体験があれば操作感も試しましょう。"]]},
focus:{label:"働き方",title:"集中できない日のための、25分から始める仕事設計",intro:"集中力を待つより、始めやすい単位に仕事を切り分けるほうが前に進みやすくなります。",sections:[["最初の25分を決める","「資料を作る」ではなく「見出しを3つ書く」のように、25分で完了できる作業を1つ選びます。"],["中断を記録する","別の用事を思い出したら実行せず、メモに残します。作業終了後に必要性を判断すると脱線を減らせます。"],["休憩も予定に入れる","25分作業したら5分離れます。数回ごとに長めの休憩を取り、疲れている日は回数を減らします。"]]},
keyboard:{label:"仕事道具",title:"キーボード選びで迷ったら、配列・打鍵感・接続から絞る",intro:"人気モデルから探す前に、自分の入力環境で外せない条件を3つに分けます。",sections:[["配列","日本語・英語配列、テンキー、矢印キーの位置は作業効率に直結します。現在使っているショートカットも洗い出しましょう。"],["打鍵感","軽さ、深さ、音の大きさを確認します。共有空間では静音性も重要です。可能なら普段の文章を試し打ちします。"],["接続","有線、Bluetooth、専用レシーバーにはそれぞれ利点があります。複数端末の切り替え、充電方法、対応OSも確認します。"]]},
bag:{label:"働き方",title:"通勤バッグの中身を軽くする、週1回の棚卸し",intro:"念のための持ち物が積み重なると、毎日の負担になります。使った頻度で分けて見直しましょう。",sections:[["全部出して3分類","毎日使う、ときどき使う、しばらく使っていない、の3つに分類します。最後の分類は一度自宅に戻します。"],["重複を減らす","充電器、文具、衛生用品など、職場に置ける物がないか確認します。小分け容器への変更も有効です。"],["金曜に5分だけ","週末前にレシートや不要な紙を出し、翌週の予定に必要な物だけを戻します。短い習慣にすると続けやすくなります。"]]}
};
const dialog=document.querySelector("#article-dialog"),content=document.querySelector("#dialog-content");
document.querySelectorAll("[data-open]").forEach(btn=>btn.addEventListener("click",()=>{const a=articles[btn.dataset.open];content.innerHTML='<p class="article-label">'+a.label+' ・ WorkMint Select編集部</p><h1>'+a.title+'</h1><p>'+a.intro+'</p>'+a.sections.map(s=>'<h2>'+s[0]+'</h2><p>'+s[1]+'</p>').join('')+'<h2>まとめ</h2><p>条件を先に整理し、公式情報と実際の使い方を照らし合わせて判断しましょう。価格や仕様は変更されるため、購入・申込み前に必ず提供元の最新情報をご確認ください。</p>';dialog.showModal();}));
document.querySelector(".dialog-close").addEventListener("click",()=>dialog.close());
dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});
document.querySelectorAll(".filters button").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".filters button").forEach(b=>b.classList.remove("active"));btn.classList.add("active");document.querySelectorAll(".article-card").forEach(card=>card.classList.toggle("hidden",btn.dataset.filter!=="all"&&card.dataset.category!==btn.dataset.filter))}));
const menu=document.querySelector(".menu-button"),nav=document.querySelector("#global-nav");menu.addEventListener("click",()=>{const open=menu.getAttribute("aria-expanded")==="true";menu.setAttribute("aria-expanded",String(!open));nav.classList.toggle("open",!open)});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");menu.setAttribute("aria-expanded","false")}));